name: eralpsoftware
description: Bu paket EralpSoftware'nin resmi açık kaynak kütüphanesidir. İçerisinde şirkette kullandığımız widget'ler ve helper'ler yer almaktadır.
version: 1.0.0
authors:
  - Cem Ergin <cem.ergin@eralpsoftware.com>
  - Burak Can Kurtarır <burak.kurtarir@eralpsoftware.com>
homepage: https://github.com/eralpsoftware/flutter_eralpsoftware

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/EralpSoftware.png